project_name: AfdianToMarkdown

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}'
    no_unique_dist_dir: true

archives:
  - format: binary
    name_template: '{{ .Binary }}'

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: '{{ .Env.GITHUB_REPOSITORY_OWNER }}'
    name: '{{ .ProjectName }}'
  prerelease: auto
  mode: append
  header: |
    ## Release {{ .Tag }}
    
    ### Downloads
  footer: |
    ### Checksums
    
    Please verify the SHA256 checksums after downloading.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'