name: Release

on:
  pull_request:
  push:
    tags:
      - 'v*'  # 当你推送匹配 vX.X.X 的标签时触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  release:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        run: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean

