name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # 当你推送匹配 vX.X.X 的标签时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Install Goreleaser
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Run Goreleaser
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
